backend:
  name: git-gateway
  branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://res.cloudinary.com/dbr4il6bz/image/upload/v1711592645/wkc5c4ijhjp8oyt2j1d3.jpg

media_folder: "src/assets"
public_folder: "/assets"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Page-Name-with-dashes-only",
          name: "slug",
          widget: "string",
        }
      - { label: "Blog Title", name: "blogTitle", widget: "string" }
      - { label: "Title Tag", name: "titleTag", widget: "string" }
      - { label: "Description", name: "blogDescription", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
